language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=4.3 TEST_EGGS=sc.social.like
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
matrix:
  fast_finish: true
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout buildout:test-eggs=$TEST_EGGS annotate
- bin/buildout buildout:test-eggs=$TEST_EGGS
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage -t "--layer=!Robot"
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
